blank_issues_enabled: false

contact_links:
  - name: ğŸ¤” Questions and Community Support
    url: https://discord.gg/9CdJeQ2XKB
    about: If you have any questions, reach out to us on Discord inside the "#support" channel.

  - name: ğŸ’¡ Feature Request
    url: https://github.com/gameguild-gg/website/discussions/categories/feature-requests
    about: Suggest a new feature for GameGuild.

  - name: âš™ï¸ Service Request
    url: https://github.com/gameguild-gg/website/discussions/categories/service-requests
    about: Request a new service integration for GameGuild.

  - name: ğŸ”§ Improvements
    url: https://github.com/gameguild-gg/website/discussions/categories/improvements
    about: Suggest improvements to existing features for GameGuild.